// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcjHLuLCQ4SPjBRoDQ2fKwGE2kX8P2w68',
    appId: '1:272532742483:web:c003895692b058a59281a6',
    messagingSenderId: '272532742483',
    projectId: 'arham-approverx',
    authDomain: 'arham-approverx.firebaseapp.com',
    storageBucket: 'arham-approverx.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiYlcXH-HOwtSGCNorNJ_ur-rJCCbaByM',
    appId: '1:272532742483:android:80f29f7d3ed44b0b9281a6',
    messagingSenderId: '272532742483',
    projectId: 'arham-approverx',
    storageBucket: 'arham-approverx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsTTLh-kqDpmTOYnXgAp4YcjbCgmvzT58',
    appId: '1:272532742483:ios:304a47d83ae2427d9281a6',
    messagingSenderId: '272532742483',
    projectId: 'arham-approverx',
    storageBucket: 'arham-approverx.firebasestorage.app',
    iosBundleId: 'com.arhamcorp.approverx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsTTLh-kqDpmTOYnXgAp4YcjbCgmvzT58',
    appId: '1:272532742483:ios:c7136ae9ba95e43d9281a6',
    messagingSenderId: '272532742483',
    projectId: 'arham-approverx',
    storageBucket: 'arham-approverx.firebasestorage.app',
    iosBundleId: 'com.example.arhamB2c',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcjHLuLCQ4SPjBRoDQ2fKwGE2kX8P2w68',
    appId: '1:272532742483:web:16b9c2057ced17b69281a6',
    messagingSenderId: '272532742483',
    projectId: 'arham-approverx',
    authDomain: 'arham-approverx.firebaseapp.com',
    storageBucket: 'arham-approverx.firebasestorage.app',
  );
}
